config/routes.rb
Rails.application.routes.draw do
  
  devise_for :owners
  
  root 'home#index'
  
  resources :bookings, except: [:show]

  namespace :admin do
      root 'hotels#index'
      resources :hotels do
        resources :rooms
      end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :room
  
  validate :start_time_cannot_be_in_the_past
	validate :start_time_cannot_be_greater_than_end_time
  
  def hotel_name
    room.hotel.name
  end
  
  def start_time_cannot_be_in_the_past
    if start_time.present? && start_time < Date.today
      errors.add(:start_time, "can't be in the past")
    end
  end

  def start_time_cannot_be_greater_than_end_time
    if start_time.present? && start_time > end_time
      errors.add(:start_time, "can't be greater than end date")
    end
  end
  
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :owner
  has_many :rooms, dependent: :destroy
  has_many :bookings, through: :rooms
  
  validates_presence_of :name, :description
  validates :description, length: { in: 2..200 }
  
  def available_rooms
    sum = 0
    rooms.map { |x| sum += x.quantity}
    return sum
  end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :hotels, dependent: :destroy
  has_many :rooms, through: :hotels
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel
  
  has_many :bookings, dependent: :destroy
  
  validates_presence_of :type_r, :quantity, :price
  
  def has_vacancy?
    self.quantity.zero? ? false : true
  end
  
  def reserve_room
    self.quantity -= 1
  end
  
  def cancel_reserve
    self.quantity += 1
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
  layout 'admin'
  
  before_action :authenticate_owner!
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < Admin::AdminController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @hotels = current_owner.hotels
    respond_with(:admin, @hotels)
  end

  def show
    respond_with(:admin, @hotel)
  end

  def new
    @hotel = current_owner.hotels.build
    respond_with(:admin, @hotel)
  end

  def edit
  end

  def create
    @hotel = current_owner.hotels.build(hotel_params)
    @hotel.save
    respond_with(:admin, @hotel)
  end

  def update
    @hotel.update(hotel_params)
    respond_with(:admin, @hotel)
  end

  def destroy
    @hotel.destroy
    respond_with(:admin, @hotel)
  end

  private
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params.require(:hotel).permit :name, :description, :owner_id
    end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::AdminController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :set_hotel, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  respond_to :html

  def index
    @rooms = @hotel.rooms
    respond_with(:admin, @hotel, @rooms)
  end

  def show
    respond_with(:admin, @hotel, @room)
  end

  def new
    @room = @hotel.rooms.build
    respond_with(:admin, @hotel, @room)
  end

  def edit
  end

  def create
    @room = @hotel.rooms.build(room_params)
    @room.save
    respond_with(:admin, @hotel, @room)
  end

  def update
    @room.update(room_params)
    respond_with(:admin, @hotel, @room)
  end

  def destroy
    @room.destroy
    respond_with(:admin, @hotel, @room)
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end
    
    def set_hotel
      @hotel = Hotel.find(params[:hotel_id])
    end

    def room_params
      params.require(:room).permit :type_r, :quantity, :price, :hotel_id
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update]

  respond_to :html

  def index
    @bookings = Booking.all
    respond_with(@bookings)
  end

  def show
    respond_with(@booking)
  end

  def new
    @booking = Booking.new
    respond_with(@booking)
  end

  def edit
  end

#  def create
#    @booking = Booking.new(booking_params)
#    @booking.room_id ||= params[:room_id]
#    binding.pry
#    @booking.save
#    respond_with(@booking)
#  end

  def create
    service = BookingService.new(params[:booking][:room_id], params[:booking][:start_time], params[:booking][:end_time])
    begin
      service.reserve!
      flash[:success] = "You are booked!" 
      redirect_to root_url
    rescue RoomNotAvailableException
      flash[:error] = "error" 
      redirect_to bookings_url
    end
  end

  def update
    @booking.update(booking_params)
    respond_with(@booking)
  end

  def destroy
    service = RemoveBookingService.new(params[:id])
    begin
      service.cancel_reserve!
      flash[:success] = "Booking was removed" 
      redirect_to bookings_url
    rescue BookingNotExistException
      flash[:error] = "error" 
      redirect_to bookings_url
    end
  end

  private
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit :start_time, :end_time, :room_id
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hotels = Hotel.includes(:rooms).all
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @hotels = Hotel.all
    respond_with(@hotels)
  end

  def show
    respond_with(@hotel)
  end

  def new
    @hotel = current_owner.hotels.build
    respond_with(@hotel)
  end

  def edit
  end

  def create
    @hotel = current_owner.hotels.build(hotel_params)
    @hotel.save
    respond_with(@hotel)
  end

  def update
    @hotel.update(hotel_params)
    respond_with(@hotel)
  end

  def destroy
    @hotel.destroy
    respond_with(@hotel)
  end

  private
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params[:hotel]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
		msg = ""		
    flash.each do |key, value|
      case key
        when "error"               	        
          msg = 'sweetAlert("Oops...", "There seems to be error.", "error");'
        when "success"
    			msg = 'swal("Good job!", "Successfully completed!", "success");'
      end    
    end
    javascript_tag(msg)
  end
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/views/admin/hotels/_form.html.erb
<%= form_for [:admin, @hotel], class: "form-signin" do |f| %>

  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> :</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, autofocus: true, class:'form-control', placeholder: "Name" %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, autocomplete: "off", maxlength: 200, class: 'form-control', placeholder: "Hotel Description" %>
  </div>

  <%= f.submit 'Submit', class: "btn btn-primary" %>
  <%= link_to 'Back', admin_hotels_path, {:class => "btn btn-default"} %>
<% end %>

app/views/admin/hotels/edit.html.erb
<div class="container">
  <div class="col-sm-4 col-sm-offset-4">
    <h1 class="form-signin-heading">Editing Hotel</h1>

    <%= render 'form' %>


  </div>
</div>

app/views/admin/hotels/index.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1">

    <h1>Listing Hotels</h1>

    <div class="panel panel-default">
    <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>List of Rooms</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @hotels.each do |hotel| %>
          <tr>
            <td><%= hotel.name %></td>
            <td><%= truncate(hotel.description) %></td>
            <td><%= link_to 'List Rooms', admin_hotel_rooms_path(hotel), class: "btn btn-raised btn-xs" %></td>
            <td style="text-align: center;">
              <%= link_to 'Detail', admin_hotel_path(hotel), class: "btn btn-raised btn-xs" %>
              <%= link_to 'Edit', edit_admin_hotel_path(hotel), class: "btn btn-raised btn-xs" %>
              <%= link_to 'Remove', admin_hotel_path(hotel), method: :delete, class: "btn btn-raised btn-xs" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    </div>

    <br>

    <%= link_to 'New Hotel', new_admin_hotel_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/admin/hotels/new.html.erb
<div class="container">
  <div class="col-sm-4 col-sm-offset-4">
    <h1 class="form-signin-heading">New Hotel</h1>

    <%= render 'form' %>

    <%= link_to 'Back', admin_hotels_path, {:class => "btn btn-default"} %>

  </div>
</div>

app/views/admin/hotels/show.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-md-offset-2">
    <div class="thumbnail">
      <%= image_tag "hotel.jpg", style: "margin-top:20px" %>
      <div class="caption">
        <h2><%= @hotel.name %></h2>
        <p><%= @hotel.description %></p>
        <br/>
        <div class="row">
          <div class="col-sm-6"><strong>Types of Rooms: </strong><%= @hotel.rooms.size %></div>
          <div class="col-sm-6"><strong>Available Rooms: </strong><%= @hotel.available_rooms %></div>
        </div>
        <br/>
        <div class="row">
          <div class="col-sm-4 col-sm-offset-4">
            <%= link_to 'Back', admin_hotels_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/rooms/_form.html.erb
<%= form_for [:admin, @hotel, @room], class: "form-signin" do |f| %>

  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> :</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :type_r, autofocus: true, class: 'form-control', placeholder: "Room Type" %>
  </div>

  <div class="form-group">
    <%= f.number_field :quantity, class: 'form-control', placeholder: "Number of rooms available", pattern: "-?[0-9]*(\.[0-9]+)?" %>
  </div>
  
  <div class="form-group">
    <%= f.number_field :price, class: 'form-control', placeholder: "Room price", pattern: "-?[0-9]*(\.[0-9]+)?", step: "0.1" %>
  </div>

  <%= f.submit 'Submit', class: "btn btn-primary" %>
  <%= link_to 'Back', admin_hotel_rooms_path, class: "btn btn-default" %>
<% end %>

app/views/admin/rooms/edit.html.erb
<div class="container">
  <div class="col-sm-4 col-sm-offset-4">
    <h1 class="form-signin-heading">Editing Room</h1>

    <%= render 'form' %>


  </div>
</div>

app/views/admin/rooms/index.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1">

    <h1>Listing Rooms</h1>

    <div class="panel panel-default">
    <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Type</th>
          <th>Quantity available</th>
          <th>Price</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= room.type_r %></td>
            <td><%= room.quantity %></td>
            <td><%= number_to_currency(room.price) %></td>
            <td style="text-align: center;">
            <%= link_to 'Detail', admin_hotel_room_path(id: room.id), class: "btn btn-raised btn-xs" %>
              <%= link_to 'Edit', edit_admin_hotel_room_path(id: room.id), class: "btn btn-raised btn-xs" %>
              <%= link_to 'Remove', admin_hotel_room_path(id: room.id), method: :delete, class: "btn btn-raised btn-xs" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    </div>

    <br>

    <%= link_to 'New Room', new_admin_hotel_room_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/admin/rooms/new.html.erb
<div class="container">
  <div class="col-sm-4 col-sm-offset-4">
    <h1 class="form-signin-heading">New Room</h1>

    <%= render 'form' %>


  </div>
</div>

app/views/admin/rooms/show.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-md-offset-2">
    <div class="thumbnail">
      <%= image_tag "room.jpg", style: "margin-top:20px" %>
      <div class="caption">
        <h2><%= @room.type_r %></h2>
        <br/>
        <div class="row">
          <div class="col-sm-6"><strong>Available: </strong><%= @room.quantity %></div>
          <div class="col-sm-6"><strong>Price: </strong><%= number_to_currency(@room.price) %></div>
        </div>
        <br/>
        <div class="row">
          <div class="col-sm-4 col-sm-offset-4">
            <%= link_to 'Back', admin_hotel_rooms_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= form_for  @booking, class: "form-signin" do |f| %>
<%= f.hidden_field(:room_id, :value => params[:room_id]) unless params[:room_id].nil? %>

  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> :</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.date_field :start_time, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.date_field :end_time, class: 'form-control' %>
  </div>
  

  <%= f.submit 'Submit', class: "btn btn-primary" %>
  <%= link_to 'Back', root_path, class: "btn btn-default" %>
<% end %>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="col-sm-4 col-sm-offset-4">
    <h1 class="form-signin-heading">Editing Booking</h1>

    <%= render 'form' %>


  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1">

    <h1>Listing Bookings</h1>

    <div class="panel panel-default">
    <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Hotel Name</th>
          <th>Room Type</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.hotel_name %></td>
            <td><%= booking.room.type_r %></td>
            <td><%= l booking.start_time, format: :custom %></td>
            <td><%= l booking.end_time, format: :custom %></td>
            <td style="text-align: center;">
              <%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-raised btn-xs" %>
              <%= link_to 'Cancel', booking_path(booking), method: :delete, class: "btn btn-raised btn-xs" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    </div>

  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="col-sm-4 col-sm-offset-4">
    <h1 class="form-signin-heading">New Booking</h1>

    <%= render 'form' %>


  </div>
</div>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/home/index.html.erb
<% if @hotels.empty? %>
  <div class="col-sm-8 col-sm-offset-4">
    <h1>There's no hotel yet.</h1>
<% else %>
  <div class="col-sm-8 col-sm-offset-2">
    <% @hotels.each do |hotel| %>
      <% if !hotel.rooms.empty? %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3><%= hotel.name %><br/>
            <small><%= hotel.description %></small></h3>
          </div>
          <div class="panel-body">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>Type</th>
                    <th>Price</th>
                    <th></th>
                  </tr>
                </thead>

                <tbody>
                  <% hotel.rooms.each do |room| %>
                    <tr>
                      <td><%= room.type_r %></td>
                      <td><%= number_to_currency(room.price) %></td>
                      <td style="text-align: center;">
                        <% if room.has_vacancy? %>
                          <%= link_to 'Booking', new_booking_path(room_id: room.id), class: "btn btn-raised btn-xs" %>
                        <% else %>
                          <p>No Vacancy</p>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<%= render :template => 'layouts/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookingSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/navbar' %>
<div class='container'>
  <%= flash_message %>
  <%= yield %>
</div>

</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Booking System', root_path, { :class => "navbar-brand" } %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <% if owner_signed_in? %>
          <li><%= link_to 'Hotels', admin_root_path %></li>
          <li>
 
          </li>
        <% end %>
        <li><%= link_to 'Reservations', bookings_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if owner_signed_in? %>
          <li><%= link_to 'Admin Panel', admin_root_path %></li>
          <li>
            <%= link_to(destroy_owner_session_path, method: 'delete') do %>
              Sair
            <% end %>
          </li>
        <% else %>
          <li><%= link_to 'Admin Panel', admin_root_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>